baseURL = "https://interieurdeco.fr/"
title = "Architecte, designer et décoratrice d’intérieur Lille : Conseil professionnel en décoration d’intérieur dans le Nord"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
paginate = "7"
theme = "spectral"
enableRobotsTXT = true

[params]
fancyTitle = "Intérieur Déco" # title for frontpage, may include image
copyright = "Manuela Faisca"
non_meta_description = "Manuela Faisca, ARCHITECTE D’INTÉRIEUR & DÉCORATRICE"
# Meta description tres important pour les moteurs de recherche
description = "Architecte d'intérieur basé sur Lille, je transforme votre espace selon vos envies et contraintes en proposant des solutions personnalisées adaptées à votre budget"
#startbuttonText = "Activate"
#startbuttonLink = "#contact_address"
body_is_markdown = true
image = "/images/banner-article1.jpg"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/qui-suis-je'
title = "Qui suis-je ?"

[[params.menu.main]]
url = '/mes-adresses-deco'
title = "Mes adresses déco"

[[params.menu.main]]
url = '/prestation-particulier'
title = "Prestations particuliers"

[[params.menu.main]]
url = '/realisations-particuliers'
title = "Réalisations particuliers"

[[params.menu.main]]
url = '/prestations-professionnels'
title = "Prestations pro"

[[params.menu.main]]
url = '/realisations-professionnels'
title = "Réalisations pro"

[[params.menu.main]]
url = '/blog/'
title = "Blog"

[[params.menu.main]]
url = '/contact'
title = "Contact"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Besoin d’un conseil en décoration dans le Nord ou ailleurs ? '
title2 = ' Un projet de rénovation ? '
body = '''
Transformez votre intérieur avec Intérieur Déco, votre décoratrice d’intérieur à Lille. Spécialiste de la conception, de l’aménagement et de la décoration d’espaces, j’imagine pour vous des ambiances uniques, chaleureuses et parfaitement adaptées à votre mode de vie.

Chaque projet est pensé pour optimiser chaque m², révéler le potentiel de votre habitat et créer un intérieur fonctionnel, harmonieux et véritablement à votre image. Vous vous assurez ainsi d’**éviter les erreurs**, de **gagner du temps** et de **faire les bons choix** dès le départ. Parce qu’un espace bien conçu, c’est un **quotidien plus fluide** et un véritable **confort de vie**.
'''
StartbuttonLink = 'mailto:contact@interieurdeco.fr'
StartbuttonText = "J'ai besoin d'être accompagné"

[params.two]
enable = true

[[params.two.section]]
img = "images/ma_mission.webp"
img_alt = "architecte d’intérieur lille"
title = '''
<blockquote>
<p><em>«&nbsp;Ma mission est de comprendre vos envies, vous proposer une réalisation sur mesure et ainsi créer un lieu unique.&nbsp;»</em></p>
</blockquote>
'''
body = 'Chaque projet est une alliance entre **esthétisme** et **fonctionnalité**. Je vous offre des **conseils en décoration sur-mesure**, en tenant compte de votre budget et des tendances actuelles. Que ce soit pour un appartement, une maison, un bureau ou un commerce, je mets ma **créativité** et mon **expertise** au service de votre projet. En tant que décoratrice d’intérieur basée à Lille, j’interviens dans tout le Nord, mais aussi à distance pour vous accompagner où que vous soyez.'


[params.video]
url = 'https://www.youtube.com/embed/QcKUNv8OBGQ'
title = 'On parle de Intérieur Déco !'
body = ''

[params.three]
enable = true
title = 'Intérieur Déco, en quelques mots'
body = ''

[[params.three.feature]]
icon = "solid fa-person-dress"
title = ""
body = "C’est avant tout moi … Manuela !"

[[params.three.feature]]
icon = "solid fa-ear-listen"
title = ""
body = "A votre écoute"

[[params.three.feature]]
icon = "solid fa-clipboard-list"
title = ""
body = "Une prise en compte de vos attentes et envies"

[[params.three.feature]]
icon = "solid fa-cubes"
title = ""
body = "Un projet 100% personnalisé et non un projet parmi tant d’autres"

[[params.three.feature]]
icon = "solid fa-comments"
title = ""
body = "Un travail collaboratif pour faire de cette maison, VOTRE maison"

[[params.three.feature]]
icon = "solid fa-earth-europe"
title = ""
body = "A distance ou à domicile ? Les deux !"

[params.cta]
enable = true
title = "Architecte et décoratrice d'intérieur à Lille dans le Nord"
body = '''
Chaque espace mérite une décoration qui lui ressemble et qui reflète la personnalité de ceux qui l’habitent. En tant que designer d’intérieur à Lille, je façonne et transforme votre intérieur en un lieu unique, fonctionnel, élégant et avec une véritable identité.<br>
Découvrez comment je peux transformer vos espaces de la conception à la sélection des matériaux.
'''


[[params.cta.link]]
href = "/qui-suis-je"
text = "Qui suis-je ?"
special = true

[[params.cta.link]]
href = "/realisations-particuliers"
text = "Réalisations"
special = false

[params.contact]
enable = true
title = "Contactez-moi"
body = '''
À distance ou à domicile ? </br>
Je suis basée en Métropole Lilloise. Ce n’est pas le cas de votre projet ? J’ai la solution ! 
Par email, au téléphone, en visio : la distance n’est pas un frein à mon activité. 
Découvrez dès maintenant mes prestations et <a href="https://interieurdeco.fr/prestation-particulier/">tarifs de décoratrice d’intérieur</a> adaptés à votre projet et à votre budget.
Contactez-moi pour en savoir plus et pour toute demande de devis.
'''
phone = "06 74 60 27 06"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "contact@interieurdeco.fr"
subject = "Nouvelle demande!"
formspree_form_id = "example_invalid"

<<<<<<< Updated upstream
body = "Zones d'intervention <br>
Lille et toute la métropole lilloise : <br> Allennes-les-Marais, Annoeullin, Anstaing, Armentières, Aubers, Baisieux, La Bassée, Bauvin, Beaucamps-Ligny, Bois-Grenier, Bondues, Bousbecque, Bouvines, Capinghem, Carnin, La Chapelle-d’Armentières, Chéreng, Comines, Croix, Cysoing, Deûlémont, Don, Emmerin, Englos, Ennetières-en-Weppes, Erquinghem-le-Sec, Erquinghem-Lys, Escobecques, Faches-Thumesnil, Forest-sur-Marque, Fournes-en-Weppes, Frelinghien, Fretin, Fromelles, Gruson, Hallennes-lez-Haubourdin, Halluin, Hantay, Haubourdin, Hem, Herlies, Houplin-Ancoisne, Houplines, Illies, Lambersart, Lannoy, Le Maisnil, Leers, Lesquin, Lezennes, Lille, Linselles, Lompret, Loos, Lys-lez-Lannoy, La Madeleine, Marcq-en-Baroeul, Marquette-lez-Lille, Marquillies, Mons-en-Baroeul, Mouvaux, Neuville-en-Ferrain, Noyelles-lès-Seclin, Pérenchies, Péronne-en-Mélantois, Prémesques, Provin, Quesnoy-sur-Deûle, Radinghem-en-Weppes, Ronchin, Roncq, Roubaix, Sailly-lez-Lannoy, Sainghin-en-Mélantois, Sainghin-en-Weppes, Saint-André-lez-Lille, Salomé, Santes, Seclin, Sequedin, Templemars, Templeuve-en-Pévèle, Toufflers, Tourcoing, Tressin, Vendeville, Verlinghem, Villeneuve-d’Ascq, Wambrechies, Wannehain, Warneton, Wasquehal, Wattignies, Wattrelos, Wavrin, Wervicq-Sud, Wicres, Willems"
#body = "Zones d'intervention <br>
#Lille et toute la métropole lilloise : <br> Allennes-les-Marais, Annoeullin, Anstaing, Armentières, Aubers, Baisieux, La Bassée, Bauvin, Beaucamps-Ligny, Bois-Grenier, Bondues, Bousbecque, Bouvines, Capinghem, Carnin, La Chapelle-d’Armentières, Chéreng, Comines, Croix, Cysoing, Deûlémont, Don, Emmerin, Englos, Ennetières-en-Weppes, Erquinghem-le-Sec, Erquinghem-Lys, Escobecques, Faches-Thumesnil, Forest-sur-Marque, Fournes-en-Weppes, Frelinghien, Fretin, Fromelles, Gruson, Hallennes-lez-Haubourdin, Halluin, Hantay, Haubourdin, Hem, Herlies, Houplin-Ancoisne, Houplines, Illies, Lambersart, Lannoy, Le Maisnil, Leers, Lesquin, Lezennes, Lille, Linselles, Lompret, Loos, Lys-lez-Lannoy, La Madeleine, Marcq-en-Baroeul, Marquette-lez-Lille, Marquillies, Mons-en-Baroeul, Mouvaux, Neuville-en-Ferrain, Noyelles-lès-Seclin, Pérenchies, Péronne-en-Mélantois, Prémesques, Provin, Quesnoy-sur-Deûle, Radinghem-en-Weppes, Ronchin, Roncq, Roubaix, Sailly-lez-Lannoy, Sainghin-en-Mélantois, Sainghin-en-Weppes, Saint-André-lez-Lille, Salomé, Santes, Seclin, Sequedin, Templemars, Templeuve-en-Pévèle, Toufflers, Tourcoing, Tressin, Vendeville, Verlinghem, Villeneuve-d’Ascq, Wambrechies, Wannehain, Warneton, Wasquehal, Wattignies, Wattrelos, Wavrin, Wervicq-Sud, Wicres, Willems"

=======
>>>>>>> Stashed changes
[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = "profile.php?id=100063743910973"
youtube = ""
instagram = "interieurdeco/"
dribble = ""

# language specific options
[languages.fr]
weight = 0
languageName = "Français"

[params.backToHome]
title = "Intérieur Déco"
